### ISSUE TITLE
신입생 모집절차 날짜 이슈

### ISSUE THREAD

**Issue by LimiteDiTempo** [themoment-team/hellogsm-front-24#126]
<img width="1498" alt="스크린샷 2024-10-10 오전 10 27 13" src="https://github.com/user-attachments/assets/daf63266-2e18-49d8-9a02-2cac8dc345d0">
안녕하십니까, 대구소프트웨어마이스터고등학교 입학 전형 시스템을 개발하는 동아리인 CNS 소속 백엔드 개발자 윤세욱입니다.
광주소프트웨어마이스터고등학교의 입학 전형 시스템을 잠시 둘러보던 중 오류를 찾아내어 말씀드립니다.
현재 신입생 모집 절차 뷰에서 올해 날짜와 요일이 일치하지 않는 오류가 보입니다.
10/24 - 목요일 
10/25 - 금요일
10/30 - 수요일
이지만 현재 뷰에서는 상이한것으로 나타납니다.

**Comment by gjaegyun** [comment]
우선, 저희 프로젝트에 관심 가져주셔서 감사드립니다.
현재는 디자이너분께 전달드려서 문제가 해결되었습니다.
앞으로 더욱 좋은 서비스를 제공 할 수 있도록 노력하겠습니다!
